"""Sphinx configuration for the pydata-sphinx-theme exploration.

Parallel to mkdocs.yml, not a replacement for it yet: the MkDocs build stays
the one CI and Read the Docs use. See docs/README-sphinx.md for what this
branch does and does not cover.
"""

from __future__ import annotations

project = "RAVEN"
copyright = "SysBioChalmers"
author = "Wang, Marcisauskas, Sanchez, Domenzain, Hermansson, Agren, Nielsen, Kerkhoven et al."

extensions = [
    "myst_parser",
    "sphinx_design",
    "sphinx_copybutton",
]

source_suffix = {".md": "markdown"}
root_doc = "index"

myst_enable_extensions = [
    "colon_fence",  # the ::: directive spelling used throughout this site
    "deflist",
    "attrs_inline",
    "dollarmath",
]
myst_heading_anchors = 4

exclude_patterns = [
    "_build",
    "conf.py",
    "README-sphinx.md",
    # Generated by scripts/gen_api_pages_sphinx.py at build time, present only
    # after that script has run once.
]

html_theme = "pydata_sphinx_theme"
# pydata-sphinx-theme's own template appends "-- {{ project }}" to whatever
# html_title is, so "RAVEN" here would double up with project = "RAVEN"
# above into a duplicated page title.
html_title = "RAVEN documentation"
html_logo = "assets/raven-icon-navy.png"
html_favicon = "assets/raven-icon-navy.png"
html_static_path = ["_static"]
html_css_files = ["custom.css"]

html_theme_options = {
    "show_nav_level": 2,
    "navigation_depth": 4,
    "show_toc_level": 2,
    "collapse_navigation": False,
    "github_url": "https://github.com/SysBioChalmers/RAVEN",
    "use_edit_page_button": False,
    "navbar_end": ["theme-switcher", "navbar-icon-links"],
}

html_context = {
    "default_mode": "auto",
}


def setup(app):
    """Run the API-reference generator before Sphinx reads the source tree.

    Mirrors what scripts/gen_api_pages.py does for the mkdocs-gen-files
    build: collect from the tracked RAVEN / raven-toolbox submodules and
    write static pages, before Sphinx's own file discovery runs.
    """
    from pathlib import Path
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))
    import gen_api_pages_sphinx

    gen_api_pages_sphinx.generate(Path(__file__).resolve().parent)
